// Core type definitions for the backend

/**
 * Represents a generated learning course.
 * 
 * @property {string} id - Unique identifier, must be UUID v4 format
 * @property {string} title - Course title, 1-200 characters, generated by AI
 * @property {string} topic - User-provided topic, 3-200 characters
 * @property {string} language - ISO 639-1 code, must be one of: 'en', 'hi', 'ta', 'te', 'bn'
 * @property {string} overview - Course description
 * @property {string[]} learning_outcomes - Array of learning objectives, 3-10 items, each 10-200 characters
 * @property {Chapter[]} chapters - Course content sections, 3-10 items
 * @property {string} created_at - ISO 8601 timestamp
 */
export interface Course {
  id: string;
  title: string;
  topic: string;
  language: string;
  overview: string;
  learning_outcomes: string[];
  chapters: Chapter[];
  created_at: string;
}

/**
 * Represents a section within a course containing learning content.
 * 
 * @property {string} title - Chapter heading, 5-100 characters
 * @property {string} content - Educational content, 100-2000 characters
 */
export interface Chapter {
  title: string;
  content: string;
}

/**
 * Lightweight representation for course listings.
 * 
 * @property {string} id - Unique identifier, UUID v4 format
 * @property {string} title - Course title
 * @property {string} topic - User-provided topic
 * @property {string} language - ISO 639-1 code
 * @property {string} created_at - ISO 8601 timestamp
 */
export interface CourseSummary {
  id: string;
  title: string;
  topic: string;
  language: string;
  created_at: string;
}

/**
 * Represents a user message to the AI tutor.
 * 
 * @property {string} message - User question, 1-1000 characters
 * @property {string} courseId - Associated course, must be valid UUID v4 and exist in database
 */
export interface ChatMessage {
  message: string;
  courseId: string;
}

/**
 * Represents the AI tutor's reply.
 * 
 * @property {string} reply - AI-generated response, 1-5000 characters
 */
export interface ChatResponse {
  reply: string;
}

/**
 * Structured error response format.
 * 
 * @property {string} error - Human-readable error message
 * @property {string} [code] - Optional error code for client handling
 * @property {unknown} [details] - Optional additional context (dev mode only)
 */
export interface ErrorResponse {
  error: string;
  code?: string;
  details?: unknown;
}

/**
 * Configuration settings for the backend application.
 * 
 * @property {string} AWS_REGION - AWS region (e.g., "us-east-1")
 * @property {string} AWS_BEDROCK_MODEL_ID - AWS Bedrock model identifier (e.g., "anthropic.claude-3-sonnet-20240229-v1:0")
 * @property {string} DATABASE_PATH - Path to SQLite database file (e.g., "./data/courses.db")
 * @property {number} PORT - Server port number, default: 3001
 * @property {string} NODE_ENV - Environment mode, default: "development"
 */
export interface Config {
  AWS_REGION: string;
  AWS_BEDROCK_MODEL_ID: string;
  DATABASE_PATH: string;
  PORT: number;
  NODE_ENV: string;
}
